/* ==========================================
 * jORLib : a free Java OR library
 * ==========================================
 *
 * Project Info:  https://github.com/jkinable/jorlib
 * Project Creator:  Joris Kinable (https://github.com/jkinable)
 *
 * (C) Copyright 2015, by Joris Kinable and Contributors.
 *
 * This program and the accompanying materials are licensed under GPLv3
 *
 */
/* -----------------
 * CutGenerator.java
 * -----------------
 * (C) Copyright 2015, by Joris Kinable and Contributors.
 *
 * Original Author:  Joris Kinable
 * Contributor(s):   -
 *
 * $Id$
 *
 * Changes
 * -------
 *
 */
package org.jorlib.frameworks.columnGeneration.master.cutGeneration;

import java.util.List;

import org.jorlib.frameworks.columnGeneration.master.MasterData;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


/**
 * 
 * @author Joris Kinable
 * @version 13-4-2015
 *
 * @param <T>
 * @param <W>
 */
public abstract class CutGenerator<T, W extends MasterData> {

	protected final Logger logger = LoggerFactory.getLogger(CutGenerator.class);
	
	protected final T modelData;
	protected W masterData;
	
	public CutGenerator(T modelData){
		this.modelData=modelData;
	}
	
	/**
	 * Separate valid inequalities
	 * @return returns true if an violated inequality has been found
	 */
	public abstract boolean generateInqualities();
	
	/**
	 * Add an inequality of the type generated by this CutGenerator to the model
	 */
	public abstract void addCut(Inequality cut);
	/**
	 * Returns all inequalities maintained by this generator
	 */
	public abstract List<Inequality> getCuts();
	
	/**
	 * Set the data class containing all the data from the master problem
	 * @param masterData
	 */
	public void setMasterData(W masterData){
		this.masterData=masterData;
	}
	
	/**
	 * Close the generator
	 */
	public abstract void close();
}
