/* ==========================================
 * jORLib : a free Java OR library
 * ==========================================
 *
 * Project Info:  https://github.com/jkinable/jorlib
 * Project Creator:  Joris Kinable (https://github.com/jkinable)
 *
 * (C) Copyright 2015, by Joris Kinable and Contributors.
 *
 * This program and the accompanying materials are licensed under GPLv3
 *
 */
/* -----------------
 * CutHandler.java
 * -----------------
 * (C) Copyright 2015, by Joris Kinable and Contributors.
 *
 * Original Author:  Joris Kinable
 * Contributor(s):   -
 *
 * $Id$
 *
 * Changes
 * -------
 *
 */
package org.jorlib.frameworks.columnGeneration.master.cutGeneration;

import java.util.ArrayList;
import java.util.Collection;
import java.util.EnumMap;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

import org.jorlib.frameworks.columnGeneration.master.MasterData;
import org.jorlib.frameworks.columnGeneration.master.cuts.Inequality;


/**
 * The CutHandler produces cuts for the master problem. Different cut types may be added.
 * 
 * @author Joris Kinable
 * @version 13-4-2015
 *
 */
public class CutHandler<T,W extends MasterData>{

	
	//private EnumMap<InequalityType, CutGenerator> cutGenerators;
//	private Map<CutGenerator, >
	private Set<CutGenerator<T,W>> cutGenerators;
	
	public CutHandler(){
//		cutGenerators=new EnumMap<InequalityType, CutGenerator>(InequalityType.class);
		cutGenerators=new LinkedHashSet<CutGenerator<T,W>>();
	}
	
	
	/**
	 * Supply the data class containing the data required by the cutGenerators.
	 * @param masterData
	 */
	public void setMasterData(W masterData){
//		for(CutGenerator cg : cutGenerators.values()){
		for(CutGenerator<T,W> cg : cutGenerators){
			cg.setMasterData(masterData);
		}
	}
	
	/**
	 * Add a new cutGenerator
	 * @param cutGenerator
	 */
	public void addCutGenerator(CutGenerator<T,W> cutGenerator){
//		cutGenerators.put(cutGenerator.inequalityType, cutGenerator);
		cutGenerators.add(cutGenerator);
	}
	
	
	/**
	 * Generates cuts for the master problem of the column generation model. Stops generation as soon as a cut has been found
	 * @return true if cuts have been found
	 */
	public boolean generateCuts(){
		boolean foundCut=false;
		//for(CutGenerator cutGen: cutGenerators.values()){
		for(CutGenerator<T,W> cutGen: cutGenerators){
			foundCut |= cutGen.generateInqualities();
			if(foundCut)
				break;
		}
		return foundCut;
	}
	
	/**
	 * Add a set of cuts from an external source. Can be used to add a number of initial cuts which are not separated from the 
	 * master problem.
	 * @param cuts
	 */
	public void addCuts(Collection<Inequality> cuts){
		System.out.println("Cuthandler: Added initial cuts: "+cuts.size());
		for(Inequality cut : cuts){
			//cutGenerators.get(cut.type).addCut(cut);
			if(!this.cutGenerators.contains(cut.maintainingGenerator))
				throw new RuntimeException("Attempt to add cut failed. CutGenerator for this type of cuts is not registered with the cut handler!");
			else
				cut.maintainingGenerator.addCut(cut);
		}
	}
	
	/**
	 * @return Gets a list of all cuts generated by the Cut Generators
	 */
	public List<Inequality> getCuts(){
		List<Inequality> cuts=new ArrayList<Inequality>();
		//for(CutGenerator cutGen : cutGenerators.values())
		for(CutGenerator<T,W> cutGen : cutGenerators)
			cuts.addAll(cutGen.getCuts());
		return cuts;
	}
	
	/**
	 * Close the Cut Generators
	 */
	public void close(){
//		for(CutGenerator cutGen : cutGenerators.values()){
		for(CutGenerator<T,W> cutGen : cutGenerators){
			cutGen.close();
		}
	}
}
